arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: localizations.dart
output-class: QSLocalizations
synthetic-package: false
preferred-supported-locales: [en]
untranslated-messages-file: untranslated.json