name: ques
description: App for tracking your bluetooth devices.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.5 <4.0.0"

dependencies:
  async: ^2.10.0
  background_fetch: ^1.1.6
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.15
  firebase_database: ^10.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_blue_plus: ^1.4.0
  flutter_comms: ^0.0.6+2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_osm_plugin: ^0.53.2
  flutter_svg: 2.0.2
  freezed_annotation: ^2.2.0
  go_router: ^6.5.0
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.8.0
  leancode_hooks: ^0.0.3+1
  location: ^4.4.0
  logging: ^1.1.1
  lottie: ^2.3.0
  maps_launcher: ^2.2.0
  oktoast: ^3.3.1
  path_provider: ^2.0.14
  provider: ^6.0.5
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.0
  json_serializable: ^6.6.1
  leancode_lint: ^2.1.0
  mockito: ^5.3.2

flutter_gen:
  output: lib/resources/

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/icons/battery/
    - assets/icons/bell/
