name: ques
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=3.3.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.2.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.0.7
  hooks_riverpod: ^2.2.0
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  leancode_hooks: ^0.0.3+1
  logging: ^1.1.1
  lottie: ^2.2.0
  oktoast: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.1.0
  leancode_lint: ^2.1.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/resources
