// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiPzJ_nJhPjpEf3wS5EDhrtXyEXukE-4Y',
    appId: '1:644324286173:android:c9b5ec7a5f1b6b51e38534',
    messagingSenderId: '644324286173',
    projectId: 'ques-1b24c',
    databaseURL:
        'https://ques-1b24c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ques-1b24c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5NerOdggM65Y0_6lAqgB6Htot0FofLk',
    appId: '1:644324286173:ios:879e1b8a187648fee38534',
    messagingSenderId: '644324286173',
    projectId: 'ques-1b24c',
    databaseURL:
        'https://ques-1b24c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ques-1b24c.appspot.com',
    iosClientId:
        '644324286173-6mjcf7k6k7aa0fvsrtbqka302fh5mvj4.apps.googleusercontent.com',
    iosBundleId: 'pl.ques.app',
  );
}
